# Generated by Django 4.1.7 on 2024-04-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/dta/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
