# Generated by Django 4.1.13 on 2024-04-17 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0002_decisiontable3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisiontable3',
            name='rule_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rm.rulecategory'),
        ),
    ]
