# Generated by Django 4.1.13 on 2024-04-17 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0003_alter_decisiontable3_rule_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionTable4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('parent_folder', models.CharField(default='', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('uuid', models.CharField(max_length=255)),
                ('locale', models.CharField(max_length=10)),
                ('body', models.TextField()),
                ('resources', models.TextField()),
                ('extracted_attributes', models.JSONField()),
                ('rule_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rm.rulecategory')),
            ],
        ),
    ]
