# Generated by Django 4.1.7 on 2024-04-12 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0003_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisiontable',
            name='extracted_decision_table',
        ),
        migrations.AddField(
            model_name='decisiontable',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='rm.category'),
        ),
        migrations.AddField(
            model_name='decisiontable',
            name='file_name',
            field=models.CharField(default='file_zip', max_length=255),
        ),
        migrations.AddField(
            model_name='decisiontable',
            name='tag_data',
            field=models.JSONField(default=dict),
        ),
    ]
