# Generated by Django 4.1.7 on 2024-04-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0005_decisiontable1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DecisionTable',
        ),
    ]
