# Generated by Django 4.1.13 on 2024-04-18 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0005_decisiontable5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisiontable5',
            name='tag_data',
        ),
    ]
