# Generated by Django 4.1.7 on 2024-04-16 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0006_delete_decisiontable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='file_zip', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('uuid', models.CharField(max_length=255)),
                ('locale', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='rm.category')),
            ],
        ),
    ]
