# Generated by Django 4.1.13 on 2024-04-11 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0007_category_actionrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisiontable1',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='rm.category'),
        ),
        migrations.AddField(
            model_name='queries',
            name='category',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='rm.category'),
        ),
    ]
