# Generated by Django 4.1.13 on 2024-04-16 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0008_decisiontable1_category_queries_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRule1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('tag_data', models.JSONField()),
                ('parent_folder', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rm.category')),
            ],
        ),
    ]
