# Generated by Django 4.1.13 on 2024-04-16 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0011_queries_parent_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRule2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('tag_data', models.JSONField()),
                ('parent_folder', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('uuid', models.CharField(max_length=36)),
                ('locale', models.CharField(max_length=10)),
                ('definition', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rm.category')),
            ],
        ),
    ]
