# Generated by Django 4.1.13 on 2024-04-16 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0012_actionrule2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionTable2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('tag_data', models.JSONField()),
                ('parent_folder', models.CharField(default='', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('uuid', models.CharField(max_length=255)),
                ('locale', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=10)),
                ('domain', models.CharField(max_length=100)),
                ('rule_description', models.TextField()),
                ('code', models.CharField(max_length=50)),
                ('resolution', models.TextField()),
                ('rule_name', models.CharField(max_length=255)),
                ('source_queue', models.CharField(max_length=100)),
                ('flight_segment_count_equal_0', models.BooleanField()),
                ('category', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='rm.category')),
            ],
        ),
    ]
